### ISSUE TITLE
Cambio instrucciones acceso moqups

### ISSUE THREAD

**Issue by pedroprieto** [interfacesweb-19-20/prototipos-mbg1819#1]
Hola Manuel,
He cambiado las instrucciones de acceso a moqups. Acabo de actualizar el fichero `README`. Ahora ya no hay que solicitar una cuenta educativa. Os puedo invitar yo a una cuenta educativa que tienen para clases. Recibirás un correo cuando esté todo listo.

Un saludo y perdona por las molestias!

**Comment by mbg1819** [comment]
Hola,

Yo me registré con la cuenta gratuita y después les solicite la licencia
estudiantes, supongo que no pasa nada, sino les escribo para que no lo
hagan.

Esperaré tu mail con la invitación.

Un saludo

**Comment by pedroprieto** [comment]
Nada, no te preocupes. El registro es necesario hacerlo. Si te conceden también la cuenta de estudiante, pues mejor.

Saludos!
